# Site settings
url             : 'https://ahmetcadirci.com.tr'
baseurl         : '/'
google_analytics: 'UA-66383788-5'
disqus_shortname: 'ahmet25'


# Seo settings
title      : 'Ahmet Çadırcı'
description: 'Ahmet Çadırcı kişisel web sitemde blog yazıları, video, podcast vb. içerikler yer almaktadır. İletişim sayfasından bana ulaşabilirsiniz.'
author     : 'Ahmet Çadırcı'
lang       : 'tr-TR'
twitter:
  username: 'ahmetcadirci25'
  card    : summary
  creator : 'ahmetcadirci25'

facebook:
  app_id   : 
  publisher: 
  admins   : 

logo: '/images/favicons/apple-touch-icon-180x180.png'
webmaster_verifications:
  google: 6pGvTVBLD2qL0rZX53G1iQDrKrplHeh2a-glZ6SZVnE
  bing  : 6E7E1B4936C97BCAC726C753E0DDD914
  yandex: ec8ac6fb02cf0aae
  alexa : 
  baidu : 

social:
  name: Ahmet Çadırcı
  links:
    - https://github.com/ahmetcadirci25

author:
  name               : 'Ahmet Çadırcı'
  email              : ahmetcadirci25@gmail.com

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate   : 5
permalink  : /:year/:title/
markdown   : kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

githubcontributions:
  username: JCotton1123 # Github username
  page_limit: 3 # Number of pages of data to grab from Github
  cache: 300 # Number of seconds to cache the data file
  
# Podcast
podcast:
  title   : Ahmet Çadırcı
  link    : https://ahmetcadirci.com.tr
  email   : ahmetcadirci25@gmail.com
  keywords: wordpress, teknoloji
  art     : https://ahmetcadirci.com.tr/images/ahmetcadirci-1400x1400.jpg
  category: Technology
  subcategories:
  - Podcasting
  subtitle: Ahmet Çadırcı — Web Geliştirici
  summary: >
    En güncel internet, teknoloji ve bilişim haberlerini podcast kayıtları üzerinden ulaşabilirsiniz.
        
plugins: ['jekyll-paginate', 'jekyll-sitemap', 'jekyll-seo-tag', 'jekyll-github-contributions']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
